--@Autor:           Elizarraras Herrera Carlos Amador
--@Fecha creación:  06/06/2022
--@Descripción:     Crea fragmentos en nodo 4.

-- FRAGMENTO: AUTO_F1_IAEH_S2 
CREATE TABLE AUTO_F1_IAEH_S2
(
  AUTO_ID    NUMBER(10, 0)    NOT NULL,
  FOTO       BLOB             NOT NULL,
  CONSTRAINT AUTO_F1_IAEH_S2_PK PRIMARY KEY(AUTO_ID)
);
-- FRAGMENTO: CLIENTE_F3_IAEH_S2 
CREATE TABLE CLIENTE_F3_IAEH_S2
(
  CLIENTE_ID            NUMBER(10, 0)    NOT NULL,
  NOMBRE                VARCHAR2(40)     NOT NULL,
  AP_PATERNO            VARCHAR2(40)     NOT NULL,
  AP_MATERNO            VARCHAR2(40),
  NUM_IDENTIFICACION    VARCHAR2(18)     NOT NULL,
  EMAIL                 VARCHAR2(500)    NOT NULL,
  CONSTRAINT CLIENTE_F3_IAEH_S2_PK PRIMARY KEY(CLIENTE_ID)
);
-- FRAGMENTO: STATUS_AUTO 
CREATE TABLE STATUS_AUTO
(
  STATUS_AUTO_ID    NUMBER(2, 0)    NOT NULL,
  CLAVE             VARCHAR2(20)    NOT NULL,
  DESCRIPCION       VARCHAR2(40)    NOT NULL,
  CONSTRAINT STATUS_AUTO_PK PRIMARY KEY(STATUS_AUTO_ID)
);
-- FRAGMENTO: HISTORICO_STATUS_F1_IAEH_S2 
CREATE TABLE HISTORICO_STATUS_F1_IAEH_S2
(
  HISTORICO_STATUS_ID    NUMBER(10, 0)    NOT NULL,
  FECHA_STATUS           DATE             NOT NULL,
  STATUS_AUTO_ID         NUMBER(2, 0)     NOT NULL,
  AUTO_ID                NUMBER(10, 0)    NOT NULL,
  CONSTRAINT HISTORICO_STATUS_F1_IAEH_S2_PK PRIMARY KEY(HISTORICO_STATUS_ID), 
  CONSTRAINT HISTORICO_STATUS_AUTO_ID_S2_FK FOREIGN KEY(AUTO_ID)
  REFERENCES AUTO_F1_IAEH_S2(AUTO_ID),
  CONSTRAINT HISTORICO_STATUS_ID_S2_FK FOREIGN KEY(STATUS_AUTO_ID)
  REFERENCES STATUS_AUTO(STATUS_AUTO_ID)
);
-- FRAGMENTO: MARCA_R_IAEH_S2 
CREATE TABLE MARCA_R_IAEH_S2
(
  MARCA_ID       NUMBER(3, 0)     NOT NULL,
  CLAVE          VARCHAR2(50)     NOT NULL,
  DESCRIPCION    VARCHAR2(500)    NOT NULL,
  ACTIVO         NUMBER(1, 0)     NOT NULL,
  CONSTRAINT MARCA_R_IAEH_S2_PK PRIMARY KEY(MARCA_ID)
);
-- FRAGMENTO: MODELO_R_IAEH_S2 
CREATE TABLE MODELO_R_IAEH_S2
(
  MODELO_ID      NUMBER(10, 0)    NOT NULL,
  CLAVE          VARCHAR2(50)     NOT NULL,
  DESCRIPCION    VARCHAR2(500)    NOT NULL,
  ACTIVO         NUMBER(1, 0),
  MARCA_ID       NUMBER(3, 0)     NOT NULL,
  CONSTRAINT MODELO_R_IAEH_S2_PK PRIMARY KEY(MODELO_ID), 
  CONSTRAINT MODELO_MARCA_ID_S2_FK FOREIGN KEY(MARCA_ID)
  REFERENCES MARCA_R_IAEH_S2(MARCA_ID)
);
-- FRAGMENTO: PAGO_AUTO_F3_IAEH_S2 
CREATE TABLE PAGO_AUTO_F3_IAEH_S2
(
  CLIENTE_ID     NUMBER(10, 0)    NOT NULL,
  AUTO_ID        NUMBER(10, 0)    NOT NULL,
  FECHA_PAGO     DATE             NOT NULL,
  IMPORTE        NUMBER(8, 2)     NOT NULL,
  RECIBO_PAGO    BLOB,
  CONSTRAINT PAGO_AUTO_F3_IAEH_S2_PK PRIMARY KEY(CLIENTE_ID, AUTO_ID), 
  CONSTRAINT PAGO_AUTO_CLIENTE_ID_S2_FK FOREIGN KEY(CLIENTE_ID)
  REFERENCES CLIENTE_F3_IAEH_S2(CLIENTE_ID),
  CONSTRAINT PAGO_AUTO_ID_S2_FK FOREIGN KEY(AUTO_ID)
  REFERENCES AUTO_F1_IAEH_S2(AUTO_ID)
);