insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (627, '100-nx', '100 Nx', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (559, '100d', '100d', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (938, '110-stawra', '110 Stawra', 76, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (939, '111-stawra', '111 Stawra', 76, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (941, '112-stawra', '112 Stawra', 76, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (560, '140d', '140d', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (561, '180d', '180d', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (624, '200-sx', '200 Sx', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (701, '206-sw', '206 Sw', 58, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (192, '2cv', '2cv', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (606, '300-gt', '300 Gt', 54, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (625, '300-zx', '300 Zx', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (595, '3000-gt', '3000 Gt', 54, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (160, '300c', '300c', 15, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (149, '300m', '300m', 15, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (700, '307-sw', '307 Sw', 58, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (505, '3200-gt', '3200 Gt', 48, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (632, '350z', '350z', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (652, '370z', '370z', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (702, '407-sw', '407 Sw', 58, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (245, '456m', '456m', 24, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (905, '4runner', '4runner', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (4, '500c', '500c', 1, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (297, '500c', '500c', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (300, '500l', '500l', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (241, '550-maranello', '550 Maranello', 24, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (242, '575m-maranello', '575m Maranello', 24, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (801, '93x', '93x', 64, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (802, '94x', '94x', 64, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (76, 'a1', 'A1', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (461, 'a112', 'A112', 42, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (61, 'a2', 'A2', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (55, 'a3', 'A3', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (46, 'a4', 'A4', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (73, 'a4-allroad-quattro', 'A4 Allroad Quattro', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (65, 'a5', 'A5', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (47, 'a6', 'A6', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (80, 'a6-allroad-quattro', 'A6 Allroad Quattro', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (77, 'a7', 'A7', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (52, 'a8', 'A8', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (355, 'accent', 'Accent', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (333, 'accord', 'Accord', 29, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (854, 'actyon', 'Actyon', 69, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (856, 'actyon-sports-pick-up', 'Actyon Sports Pick Up', 69, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (686, 'adam', 'Adam', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (611, 'aero-8', 'Aero 8', 55, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (667, 'agila', 'Agila', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (133, 'alero', 'Alero', 14, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (811, 'alhambra', 'Alhambra', 66, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (59, 'allroad-quattro', 'Allroad Quattro', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (628, 'almera', 'Almera', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (630, 'almera-tino', 'Almera Tino', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (763, 'alpine', 'Alpine', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (814, 'altea', 'Altea', 66, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (816, 'altea-freetrack', 'Altea Freetrack', 66, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (815, 'altea-xl', 'Altea Xl', 66, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (878, 'alto', 'Alto', 71, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (970, 'amarok', 'Amarok', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (684, 'ampera', 'Ampera', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (805, 'anibal', 'Anibal', 65, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (806, 'anibal-pick-up', 'Anibal Pick Up', 65, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (671, 'antara', 'Antara', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (221, 'applause', 'Applause', 21, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (210, 'aranos', 'Aranos', 19, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (292, 'argenta', 'Argenta', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (903, 'aria', 'Aria', 73, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (93, 'arnage', 'Arnage', 10, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (812, 'arosa', 'Arosa', 66, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (681, 'ascona', 'Ascona', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (657, 'astra', 'Astra', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (127, 'astro', 'Astro', 14, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (607, 'asx', 'Asx', 54, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (358, 'atos', 'Atos', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (360, 'atos-prime', 'Atos Prime', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (916, 'auris', 'Auris', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (746, 'avantime', 'Avantime', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (235, 'avenger', 'Avenger', 23, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (917, 'avensis', 'Avensis', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (924, 'avensis-verso', 'Avensis Verso', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (444, 'aventador', 'Aventador', 41, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (138, 'aveo', 'Aveo', 14, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (165, 'ax', 'Ax', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (927, 'aygo', 'Aygo', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (92, 'azure', 'Azure', 10, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (535, 'b2500', 'B2500', 50, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (865, 'b9-tribeca', 'B9 Tribeca', 70, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (876, 'baleno', 'Baleno', 71, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (274, 'barchetta', 'Barchetta', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (971, 'beetle', 'Beetle', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (185, 'berlingo', 'Berlingo', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (195, 'berlingo-first', 'Berlingo First', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (713, 'bipper', 'Bipper', 58, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (511, 'biturbo', 'Biturbo', 48, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (126, 'blazer', 'Blazer', 14, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (124, 'bls', 'Bls', 13, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (647, 'bluebird', 'Bluebird', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (328, 'bmax', 'Bmax', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (496, 'bolero-pickup', 'Bolero Pickup', 47, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (949, 'bora', 'Bora', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (707, 'boxer', 'Boxer', 58, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (726, 'boxster', 'Boxster', 60, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (277, 'brava', 'Brava', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (275, 'bravo', 'Bravo', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (19, 'brera', 'Brera', 2, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (89, 'brooklands', 'Brooklands', 10, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (872, 'brz', 'Brz', 70, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (536, 'bt50', 'Bt50', 50, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (186, 'bx', 'Bx', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (177, 'c1', 'C1', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (182, 'c15', 'C15', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (170, 'c2', 'C2', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (187, 'c25', 'C25', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (175, 'c3', 'C3', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (196, 'c3-picasso', 'C3 Picasso', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (176, 'c3-pluriel', 'C3 Pluriel', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (995, 'c30', 'C30', 78, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (172, 'c4', 'C4', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (201, 'c4-aircross', 'C4 Aircross', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (180, 'c4-picasso', 'C4 Picasso', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (194, 'c4-sedan', 'C4 Sedan', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (174, 'c5', 'C5', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (178, 'c6', 'C6', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (991, 'c70', 'C70', 78, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (168, 'c8', 'C8', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (841, 'cabrio', 'Cabrio', 68, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (53, 'cabriolet', 'Cabriolet', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (791, 'cabriolet', 'Cabriolet', 63, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (643, 'cabstar', 'Cabstar', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (642, 'cabstar-e', 'Cabstar E', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (956, 'caddy', 'Caddy', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (233, 'caliber', 'Caliber', 23, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (659, 'calibra', 'Calibra', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (259, 'california', 'California', 24, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (966, 'california', 'California', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (131, 'camaro', 'Camaro', 14, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (645, 'camion', 'Camion', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (906, 'camry', 'Camry', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (605, 'canter', 'Canter', 54, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (324, 'capri', 'Capri', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (141, 'captiva', 'Captiva', 14, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (960, 'caravelle', 'Caravelle', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (419, 'carens', 'Carens', 39, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (904, 'carina-e', 'Carina E', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (596, 'carisma', 'Carisma', 54, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (416, 'carnival', 'Carnival', 39, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (728, 'carrera-gt', 'Carrera Gt', 60, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (727, 'cayenne', 'Cayenne', 60, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (729, 'cayman', 'Cayman', 60, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (973, 'cc', 'Cc', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (181, 'ccrosser', 'Ccrosser', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (425, 'ceed', 'Ceed', 39, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (433, 'ceed-sportswagon', 'Ceed Sportswagon', 39, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (426, 'ceed-sporty-wagon', 'Ceed Sporty Wagon', 39, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (908, 'celica', 'Celica', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (202, 'celysee', 'Celysee', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (421, 'cerato', 'Cerato', 39, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (222, 'charade', 'Charade', 21, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (404, 'cherokee', 'Cherokee', 38, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (263, 'cinquecento', 'Cinquecento', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (836, 'citigo', 'Citigo', 67, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (839, 'citycoupe', 'Citycoupe', 68, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (334, 'civic', 'Civic', 29, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (499, 'cj', 'Cj', 47, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (414, 'clarus', 'Clarus', 39, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (550, 'clase-a', 'Clase A', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (558, 'clase-b', 'Clase B', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (540, 'clase-c', 'Clase C', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (544, 'clase-cl', 'Clase Cl', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (577, 'clase-clc', 'Clase Clc', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (549, 'clase-clk', 'Clase Clk', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (555, 'clase-cls', 'Clase Cls', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (541, 'clase-e', 'Clase E', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (545, 'clase-g', 'Clase G', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (557, 'clase-gl', 'Clase Gl', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (578, 'clase-glk', 'Clase Glk', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (551, 'clase-m', 'Clase M', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (556, 'clase-r', 'Clase R', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (543, 'clase-s', 'Clase S', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (542, 'clase-sl', 'Clase Sl', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (571, 'clase-sl-r129', 'Clase Sl R129', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (546, 'clase-slk', 'Clase Slk', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (547, 'clase-v', 'Clase V', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (985, 'classic', 'Classic', 78, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (739, 'clio', 'Clio', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (749, 'clio-campus', 'Clio Campus', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (316, 'cmax', 'Cmax', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (591, 'colt', 'Colt', 54, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (673, 'combo', 'Combo', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (406, 'commander', 'Commander', 38, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (104, 'compact', 'Compact', 12, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (213, 'compact', 'Compact', 19, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (407, 'compass', 'Compass', 38, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (346, 'concerto', 'Concerto', 29, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (204, 'contac', 'Contac', 18, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (91, 'continental', 'Continental', 10, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (95, 'continental-flying-spur', 'Continental Flying Spur', 10, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (94, 'continental-gt', 'Continental Gt', 10, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (99, 'continental-gtc', 'Continental Gtc', 10, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (100, 'continental-supersports', 'Continental Supersports', 10, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (808, 'cordoba', 'Cordoba', 66, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (780, 'corniche', 'Corniche', 62, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (915, 'corolla', 'Corolla', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (926, 'corolla-sedan', 'Corolla Sedan', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (925, 'corolla-verso', 'Corolla Verso', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (946, 'corrado', 'Corrado', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (660, 'corsa', 'Corsa', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (125, 'corvette', 'Corvette', 14, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (203, 'corvette', 'Corvette', 17, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (312, 'cougar', 'Cougar', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (587, 'countryman', 'Countryman', 52, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (1007, 'countryman', 'Countryman', 53, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (49, 'coupe', 'Coupe', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (269, 'coupe', 'Coupe', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (357, 'coupe', 'Coupe', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (506, 'coupe', 'Coupe', 48, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (788, 'coupe', 'Coupe', 63, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (319, 'courier', 'Courier', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (965, 'crafter', 'Crafter', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (262, 'croma', 'Croma', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (842, 'crossblade', 'Crossblade', 68, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (159, 'crossfire', 'Crossfire', 15, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (18, 'crosswagon', 'Crosswagon', 2, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (143, 'cruze', 'Cruze', 14, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (339, 'crv', 'Crv', 29, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (335, 'crx', 'Crx', 29, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (348, 'crz', 'Crz', 29, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (493, 'ct', 'Ct', 45, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (120, 'cts', 'Cts', 13, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (653, 'cube', 'Cube', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (188, 'cx', 'Cx', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (539, 'cx5', 'Cx5', 50, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (533, 'cx7', 'Cx7', 50, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (44, 'cygnet', 'Cygnet', 6, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (198, 'czero', 'Czero', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (389, 'd-max', 'D Max', 34, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (29, 'dacia', 'Dacia', 3, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (393, 'daily', 'Daily', 35, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (395, 'daily', 'Daily', 36, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (32, 'db7', 'Db7', 6, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (34, 'db9', 'Db9', 6, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (38, 'dbs', 'Dbs', 6, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (448, 'dedra', 'Dedra', 42, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (465, 'defender', 'Defender', 43, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (445, 'delta', 'Delta', 42, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (526, 'demio', 'Demio', 50, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (88, 'diesel', 'Diesel', 9, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (466, 'discovery', 'Discovery', 43, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (469, 'discovery-4', 'Discovery 4', 43, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (391, 'dmax', 'Dmax', 34, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (288, 'doblo', 'Doblo', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (287, 'doblo-cargo', 'Doblo Cargo', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (229, 'double-six', 'Double Six', 22, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (197, 'ds3', 'Ds3', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (199, 'ds4', 'Ds4', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (200, 'ds5', 'Ds5', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (286, 'ducato', 'Ducato', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (207, 'duster', 'Duster', 18, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (396, 'duty', 'Duty', 36, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (929, 'dyna', 'Dyna', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (597, 'eclipse', 'Eclipse', 54, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (98, 'eight', 'Eight', 10, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (119, 'el-dorado', 'El Dorado', 13, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (354, 'elantra', 'Elantra', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (385, 'elba', 'Elba', 33, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (494, 'elise', 'Elise', 46, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (248, 'enzo', 'Enzo', 24, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (959, 'eos', 'Eos', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (140, 'epica', 'Epica', 14, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (123, 'escalade', 'Escalade', 13, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (302, 'escort', 'Escort', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (742, 'espace', 'Espace', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (656, 'evalia', 'Evalia', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (129, 'evanda', 'Evanda', 14, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (216, 'evanda', 'Evanda', 19, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (167, 'evasion', 'Evasion', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (382, 'ex', 'Ex', 32, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (330, 'exceed', 'Exceed', 27, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (821, 'exeo', 'Exeo', 66, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (495, 'exige', 'Exige', 46, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (26, 'expander', 'Expander', 3, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (308, 'explorer', 'Explorer', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (751, 'express', 'Express', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (237, 'f355', 'F355', 24, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (255, 'f40', 'F40', 24, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (239, 'f430', 'F430', 24, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (247, 'f50', 'F50', 24, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (240, 'f512-m', 'F512 M', 24, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (827, 'fabia', 'Fabia', 67, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (846, 'family', 'Family', 69, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (832, 'favorit', 'Favorit', 67, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (823, 'felicia', 'Felicia', 67, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (224, 'feroza', 'Feroza', 21, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (261, 'ff', 'Ff', 24, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (306, 'fiesta', 'Fiesta', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (285, 'fiorino', 'Fiorino', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (723, 'firebird', 'Firebird', 59, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (772, 'fluence', 'Fluence', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (303, 'focus', 'Focus', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (313, 'focus-cmax', 'Focus Cmax', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (863, 'forester', 'Forester', 70, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (844, 'forfour', 'Forfour', 68, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (824, 'forman', 'Forman', 67, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (840, 'fortwo', 'Fortwo', 68, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (958, 'fox', 'Fox', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (101, 'freeclimber-diesel', 'Freeclimber Diesel', 11, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (467, 'freelander', 'Freelander', 43, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (298, 'freemont', 'Freemont', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (662, 'frontera', 'Frontera', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (345, 'frv', 'Frv', 29, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (764, 'fuego', 'Fuego', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (314, 'fusion', 'Fusion', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (383, 'fx', 'Fx', 32, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (381, 'g', 'G', 32, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (864, 'g3x-justy', 'G3x Justy', 70, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (590, 'galant', 'Galant', 54, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (309, 'galaxy', 'Galaxy', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (442, 'gallardo', 'Gallardo', 41, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (378, 'genesis', 'Genesis', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (366, 'getz', 'Getz', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (502, 'ghibli', 'Ghibli', 48, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (23, 'giulietta', 'Giulietta', 2, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (498, 'goa', 'Goa', 47, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (497, 'goa-pickup', 'Goa Pickup', 47, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (943, 'golf', 'Golf', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (957, 'golf-plus', 'Golf Plus', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (325, 'granada', 'Granada', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (514, 'grancabrio', 'Grancabrio', 48, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (179, 'grand-c4-picasso', 'Grand C4 Picasso', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (405, 'grand-cherokee', 'Grand Cherokee', 38, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (327, 'grand-cmax', 'Grand Cmax', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (745, 'grand-espace', 'Grand Espace', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (775, 'grand-kangoo-combi', 'Grand Kangoo Combi', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (769, 'grand-modus', 'Grand Modus', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (898, 'grand-safari', 'Grand Safari', 73, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (748, 'grand-scenic', 'Grand Scenic', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (881, 'grand-vitara', 'Grand Vitara', 71, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (884, 'grand-vitara-xl7', 'Grand Vitara Xl7', 71, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (150, 'grand-voyager', 'Grand Voyager', 15, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (2, 'grande-punto', 'Grande Punto', 1, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (266, 'grande-punto', 'Grande Punto', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (370, 'grandeur', 'Grandeur', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (603, 'grandis', 'Grandis', 54, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (508, 'gransport', 'Gransport', 48, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (509, 'granturismo', 'Granturismo', 48, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (489, 'gs', 'Gs', 45, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (474, 'gs300', 'Gs300', 45, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (477, 'gs430', 'Gs430', 45, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (485, 'gs450h', 'Gs450h', 45, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (478, 'gs460', 'Gs460', 45, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (189, 'gsa', 'Gsa', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (17, 'gt', 'Gt', 2, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (672, 'gt', 'Gt', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (934, 'gt86', 'Gt86', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (651, 'gtr', 'Gtr', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (14, 'gtv', 'Gtv', 2, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (359, 'h1', 'H1', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (349, 'h2', 'H2', 30, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (350, 'h3', 'H3', 30, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (351, 'h3t', 'H3t', 30, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (142, 'hhr', 'Hhr', 14, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (928, 'hilux', 'Hilux', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (891, 'horizon', 'Horizon', 72, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (340, 'hrv', 'Hrv', 29, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (371, 'i10', 'I10', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (375, 'i20', 'I20', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (368, 'i30', 'I30', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (379, 'i40', 'I40', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (372, 'i800', 'I800', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (807, 'ibiza', 'Ibiza', 66, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (281, 'idea', 'Idea', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (882, 'ignis', 'Ignis', 71, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (608, 'imiev', 'Imiev', 54, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (859, 'impreza', 'Impreza', 70, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (818, 'inca', 'Inca', 66, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (896, 'indica', 'Indica', 73, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (897, 'indigo', 'Indigo', 73, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (347, 'insight', 'Insight', 29, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (682, 'insignia', 'Insignia', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (719, 'ion', 'Ion', 58, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (932, 'iq', 'Iq', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (490, 'is', 'Is', 45, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (475, 'is200', 'Is200', 45, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (483, 'is220d', 'Is220d', 45, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (481, 'is250', 'Is250', 45, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (480, 'is300', 'Is300', 45, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (377, 'ix20', 'Ix20', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (376, 'ix35', 'Ix35', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (374, 'ix55', 'Ix55', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (709, 'j5', 'J5', 58, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (344, 'jazz', 'Jazz', 29, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (950, 'jetta', 'Jetta', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (880, 'jimny', 'Jimny', 71, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (417, 'joice', 'Joice', 39, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (236, 'journey', 'Journey', 23, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (654, 'juke', 'Juke', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (183, 'jumper', 'Jumper', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (184, 'jumpy', 'Jumpy', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (861, 'justy', 'Justy', 70, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (446, 'k', 'K', 42, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (429, 'k2500', 'K2500', 39, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (428, 'k2500-frontier', 'K2500 Frontier', 39, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (847, 'k4d', 'K4d', 69, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (310, 'ka', 'Ka', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (676, 'kadett', 'Kadett', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (439, 'kalina', 'Kalina', 40, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (137, 'kalos', 'Kalos', 14, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (219, 'kalos', 'Kalos', 19, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (754, 'kangoo', 'Kangoo', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (770, 'kangoo-combi', 'Kangoo Combi', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (458, 'kappa', 'Kappa', 42, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (887, 'kizashi', 'Kizashi', 71, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (857, 'kodando', 'Kodando', 69, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (771, 'koleos', 'Koleos', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (845, 'korando', 'Korando', 69, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (849, 'korando-kj', 'Korando Kj', 69, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (326, 'kuga', 'Kuga', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (853, 'kyron', 'Kyron', 69, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (604, 'l200', 'L200', 54, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (139, 'lacetti', 'Lacetti', 14, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (220, 'lacetti', 'Lacetti', 19, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (738, 'laguna', 'Laguna', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (602, 'lancer', 'Lancer', 54, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (913, 'land-cruiser', 'Land Cruiser', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (912, 'land-cruiser-100', 'Land Cruiser 100', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (930, 'land-cruiser-200', 'Land Cruiser 200', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (911, 'land-cruiser-80', 'Land Cruiser 80', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (914, 'land-cruiser-90', 'Land Cruiser 90', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (211, 'lanos', 'Lanos', 19, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (352, 'lantra', 'Lantra', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (774, 'latitude', 'Latitude', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (161, 'le-baron', 'Le Baron', 15, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (655, 'leaf', 'Leaf', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (858, 'legacy', 'Legacy', 70, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (215, 'leganza', 'Leganza', 19, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (338, 'legend', 'Legend', 29, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (813, 'leon', 'Leon', 66, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (883, 'liana', 'Liana', 71, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (283, 'linea', 'Linea', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (191, 'lna', 'Lna', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (208, 'lodgy', 'Lodgy', 18, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (205, 'logan', 'Logan', 18, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (341, 'logo', 'Logo', 29, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (488, 'ls', 'Ls', 45, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (472, 'ls400', 'Ls400', 45, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (473, 'ls430', 'Ls430', 45, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (486, 'ls460', 'Ls460', 45, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (487, 'ls600h', 'Ls600h', 45, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (963, 'lt', 'Lt', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (948, 'lupo', 'Lupo', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (449, 'lybra', 'Lybra', 42, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (384, 'm', 'M', 32, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (85, 'maestro', 'Maestro', 8, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (418, 'magentis', 'Magentis', 39, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (819, 'malaga', 'Malaga', 66, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (147, 'malibu', 'Malibu', 14, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (680, 'manta', 'Manta', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (810, 'marbella', 'Marbella', 66, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (273, 'marea', 'Marea', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (873, 'maruti', 'Maruti', 71, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (755, 'mascott', 'Mascott', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (394, 'massif', 'Massif', 35, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (753, 'master', 'Master', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (756, 'master-propulsion', 'Master Propulsion', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (132, 'matiz', 'Matiz', 14, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (217, 'matiz', 'Matiz', 19, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (365, 'matrix', 'Matrix', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (301, 'maverick', 'Maverick', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (644, 'maxima', 'Maxima', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (623, 'maxima-qx', 'Maxima Qx', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (757, 'maxity', 'Maxity', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (471, 'maxus', 'Maxus', 44, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (515, 'maybach', 'Maybach', 49, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (530, 'mazda2', 'Mazda2', 50, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (524, 'mazda3', 'Mazda3', 50, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (532, 'mazda5', 'Mazda5', 50, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (529, 'mazda6', 'Mazda6', 50, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (736, 'megane', 'Megane', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (670, 'meriva', 'Meriva', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (86, 'metro', 'Metro', 8, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (580, 'mgf', 'Mgf', 52, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (618, 'micra', 'Micra', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (822, 'mii', 'Mii', 66, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (83, 'mini', 'Mini', 8, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (586, 'mini', 'Mini', 52, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (1006, 'mini', 'Mini', 53, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (793, 'mini', 'Mini', 63, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (87, 'mini-moke', 'Mini Moke', 8, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (386, 'minitre', 'Minitre', 33, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (25, 'mito', 'Mito', 2, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (750, 'modus', 'Modus', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (685, 'mokka', 'Mokka', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (304, 'mondeo', 'Mondeo', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (257, 'mondial', 'Mondial', 24, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (84, 'montego', 'Montego', 8, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (664, 'monterey', 'Monterey', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (589, 'montero', 'Montero', 54, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (600, 'montero-io', 'Montero Io', 54, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (599, 'montero-sport', 'Montero Sport', 54, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (677, 'monza', 'Monza', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (674, 'movano', 'Movano', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (525, 'mpv', 'Mpv', 50, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (921, 'mr2', 'Mr2', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (97, 'mulsanne', 'Mulsanne', 10, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (280, 'multipla', 'Multipla', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (955, 'multivan', 'Multivan', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (633, 'murano', 'Murano', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (443, 'murcielago', 'Murcielago', 41, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (455, 'musa', 'Musa', 42, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (848, 'musso', 'Musso', 69, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (521, 'mx3', 'Mx3', 50, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (523, 'mx5', 'Mx5', 50, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (537, 'mx6', 'Mx6', 50, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (641, 'navara', 'Navara', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (193, 'nemo', 'Nemo', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (152, 'neon', 'Neon', 15, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (741, 'nevada', 'Nevada', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (951, 'new-beetle', 'New Beetle', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (157, 'new-yorker', 'New Yorker', 15, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (209, 'nexia', 'Nexia', 19, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (234, 'nitro', 'Nitro', 23, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (435, 'niva', 'Niva', 40, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (634, 'note', 'Note', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (648, 'np300-pick-up', 'Np300 Pick Up', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (337, 'nsx', 'Nsx', 29, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (128, 'nubira', 'Nubira', 14, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (212, 'nubira', 'Nubira', 19, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (214, 'nubira-compact', 'Nubira Compact', 19, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (825, 'octavia', 'Octavia', 67, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (826, 'octavia-tour', 'Octavia Tour', 67, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (661, 'omega', 'Omega', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (423, 'opirus', 'Opirus', 39, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (432, 'optima', 'Optima', 39, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (322, 'orion', 'Orion', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (145, 'orlando', 'Orlando', 14, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (862, 'outback', 'Outback', 70, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (601, 'outlander', 'Outlander', 54, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (588, 'paceman', 'Paceman', 52, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (1008, 'paceman', 'Paceman', 53, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (278, 'palio-weekend', 'Palio Weekend', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (734, 'panamera', 'Panamera', 60, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (267, 'panda', 'Panda', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (299, 'panda-classic', 'Panda Classic', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (778, 'park-ward', 'Park Ward', 62, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (708, 'partner', 'Partner', 58, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (714, 'partner-origin', 'Partner Origin', 58, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (910, 'paseo', 'Paseo', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (942, 'passat', 'Passat', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (969, 'passat-cc', 'Passat Cc', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (629, 'pathfinder', 'Pathfinder', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (409, 'patriot', 'Patriot', 38, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (622, 'patrol', 'Patrol', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (626, 'patrol-gr', 'Patrol Gr', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (952, 'phaeton', 'Phaeton', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (781, 'phantom', 'Phantom', 62, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (454, 'phedra', 'Phedra', 42, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (424, 'picanto', 'Picanto', 39, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (323, 'pick-up', 'Pick Up', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (388, 'pick-up', 'Pick Up', 34, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (640, 'pickup', 'Pickup', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (831, 'pickup', 'Pickup', 67, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (918, 'picnic', 'Picnic', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (500, 'pikup', 'Pikup', 47, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (650, 'pixo', 'Pixo', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (615, 'plus-4', 'Plus 4', 55, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (610, 'plus-8', 'Plus 8', 55, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (945, 'polo', 'Polo', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (369, 'pony', 'Pony', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (646, 'prairie', 'Prairie', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (336, 'prelude', 'Prelude', 29, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (527, 'premacy', 'Premacy', 50, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (922, 'previa', 'Previa', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (413, 'pride', 'Pride', 39, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (620, 'primera', 'Primera', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (441, 'priora', 'Priora', 40, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (460, 'prisma', 'Prisma', 42, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (923, 'prius', 'Prius', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (307, 'probe', 'Probe', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (427, 'proceed', 'Proceed', 39, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (158, 'pt-cruiser', 'Pt Cruiser', 15, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (311, 'puma', 'Puma', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (6, 'punto', 'Punto', 1, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (265, 'punto', 'Punto', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (294, 'punto-classic', 'Punto Classic', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (3, 'punto-evo', 'Punto Evo', 1, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (296, 'punto-evo', 'Punto Evo', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (79, 'q3', 'Q3', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (72, 'q5', 'Q5', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (63, 'q7', 'Q7', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (635, 'qashqai', 'Qashqai', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (649, 'qashqai2', 'Qashqai2', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (504, 'quattroporte', 'Quattroporte', 48, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (295, 'qubo', 'Qubo', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (766, 'r11', 'R11', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (765, 'r18', 'R18', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (758, 'r19', 'R19', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (761, 'r21', 'R21', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (759, 'r25', 'R25', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (762, 'r4', 'R4', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (760, 'r5', 'R5', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (768, 'r6', 'R6', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (64, 'r8', 'R8', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (767, 'r9', 'R9', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (464, 'range-rover', 'Range Rover', 43, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (470, 'range-rover-evoque', 'Range Rover Evoque', 43, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (468, 'range-rover-sport', 'Range Rover Sport', 43, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (320, 'ranger', 'Ranger', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (837, 'rapid', 'Rapid', 67, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (43, 'rapide', 'Rapide', 6, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (907, 'rav4', 'Rav4', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (717, 'rcz', 'Rcz', 58, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (290, 'regata', 'Regata', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (679, 'rekord', 'Rekord', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (850, 'rexton', 'Rexton', 69, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (851, 'rexton-ii', 'Rexton Ii', 69, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (420, 'rio', 'Rio', 39, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (293, 'ritmo', 'Ritmo', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (613, 'roadster', 'Roadster', 55, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (843, 'roadster', 'Roadster', 68, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (223, 'rocky', 'Rocky', 21, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (30, 'rocsta', 'Rocsta', 4, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (31, 'rocsta', 'Rocsta', 5, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (390, 'rodeo', 'Rodeo', 34, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (852, 'rodius', 'Rodius', 69, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (820, 'ronda', 'Ronda', 66, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (829, 'roomster', 'Roomster', 67, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (51, 'rs2', 'Rs2', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (78, 'rs3', 'Rs3', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (60, 'rs4', 'Rs4', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (75, 'rs5', 'Rs5', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (62, 'rs6', 'Rs6', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (492, 'rx', 'Rx', 45, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (476, 'rx300', 'Rx300', 45, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (484, 'rx350', 'Rx350', 45, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (482, 'rx400h', 'Rx400h', 45, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (522, 'rx7', 'Rx7', 50, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (531, 'rx8', 'Rx8', 50, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (834, 's', 'S', 67, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (50, 's2', 'S2', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (342, 's2000', 'S2000', 29, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (58, 's3', 'S3', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (56, 's4', 'S4', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (986, 's40', 'S40', 78, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (66, 's5', 'S5', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (48, 's6', 'S6', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (993, 's60', 'S60', 78, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (81, 's7', 'S7', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (976, 's70', 'S70', 78, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (54, 's8', 'S8', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (992, 's80', 'S80', 78, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (983, 's90', 'S90', 78, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (895, 'safari', 'Safari', 73, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (737, 'safrane', 'Safrane', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (436, 'sagona', 'Sagona', 40, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (434, 'samara', 'Samara', 40, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (888, 'samba', 'Samba', 72, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (877, 'samurai', 'Samurai', 71, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (206, 'sandero', 'Sandero', 18, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (363, 'santa-fe', 'Santa Fe', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (331, 'santamo', 'Santamo', 27, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (967, 'santana', 'Santana', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (162, 'saratoga', 'Saratoga', 15, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (169, 'saxo', 'Saxo', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (491, 'sc', 'Sc', 45, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (479, 'sc430', 'Sc430', 45, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (744, 'scenic', 'Scenic', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (968, 'scirocco', 'Scirocco', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (305, 'scorpio', 'Scorpio', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (356, 'scoupe', 'Scoupe', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (830, 'scout', 'Scout', 67, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (796, 'sd', 'Sd', 63, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (155, 'sebring', 'Sebring', 15, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (156, 'sebring-200c', 'Sebring 200c', 15, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (282, 'sedici', 'Sedici', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (264, 'seicento', 'Seicento', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (678, 'senator', 'Senator', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (411, 'sephia', 'Sephia', 39, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (412, 'sephia-ii', 'Sephia Ii', 39, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (621, 'serena', 'Serena', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (113, 'serie-1', 'Serie 1', 12, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (440, 'serie-2100', 'Serie 2100', 40, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (102, 'serie-3', 'Serie 3', 12, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (103, 'serie-5', 'Serie 5', 12, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (111, 'serie-6', 'Serie 6', 12, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (105, 'serie-7', 'Serie 7', 12, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (106, 'serie-8', 'Serie 8', 12, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (534, 'serie-b', 'Serie B', 50, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (227, 'serie-xj', 'Serie Xj', 22, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (397, 'serie-xj', 'Serie Xj', 37, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (398, 'serie-xk', 'Serie Xk', 37, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (231, 'series-iii', 'Series Iii', 22, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (117, 'seville', 'Seville', 13, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (503, 'shamal', 'Shamal', 48, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (947, 'sharan', 'Sharan', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (415, 'shuma', 'Shuma', 39, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (321, 'sierra', 'Sierra', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (669, 'signum', 'Signum', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (779, 'silver-seraph', 'Silver Seraph', 62, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (777, 'silver-spur', 'Silver Spur', 62, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (783, 'silvier', 'Silvier', 62, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (665, 'sintra', 'Sintra', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (226, 'sirion', 'Sirion', 21, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (776, 'siver-dawn', 'Siver Dawn', 62, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (230, 'six', 'Six', 22, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (553, 'slklasse', 'Slklasse', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (554, 'slr-mclaren', 'Slr Mclaren', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (579, 'sls-amg', 'Sls Amg', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (838, 'smart', 'Smart', 68, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (317, 'smax', 'Smax', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (890, 'solara', 'Solara', 72, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (353, 'sonata', 'Sonata', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (373, 'sonata-fl', 'Sonata Fl', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (422, 'sorento', 'Sorento', 39, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (430, 'soul', 'Soul', 39, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (594, 'space-gear', 'Space Gear', 54, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (593, 'space-runner', 'Space Runner', 54, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (598, 'space-star', 'Space Star', 54, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (592, 'space-wagon', 'Space Wagon', 54, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (144, 'spark', 'Spark', 14, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (668, 'speedster', 'Speedster', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (15, 'spider', 'Spider', 2, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (743, 'spider', 'Spider', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (886, 'splash', 'Splash', 71, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (410, 'sportage', 'Sportage', 39, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (855, 'sports-pick-up', 'Sports Pick Up', 69, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (24, 'sprint', 'Sprint', 2, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (562, 'sprinter', 'Sprinter', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (507, 'spyder', 'Spyder', 48, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (82, 'sq5', 'Sq5', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (122, 'srx', 'Srx', 13, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (437, 'stawra-2110', 'Stawra 2110', 40, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (276, 'stilo', 'Stilo', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (289, 'strada', 'Strada', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (154, 'stratus', 'Stratus', 15, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (343, 'stream', 'Stream', 29, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (315, 'streetka', 'Streetka', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (795, 'streetwise', 'Streetwise', 63, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (118, 'sts', 'Sts', 13, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (400, 'stype', 'Stype', 37, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (894, 'sumo', 'Sumo', 73, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (619, 'sunny', 'Sunny', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (332, 'super-exceed', 'Super Exceed', 27, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (249, 'superamerica', 'Superamerica', 24, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (828, 'superb', 'Superb', 67, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (909, 'supra', 'Supra', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (860, 'svx', 'Svx', 70, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (874, 'swift', 'Swift', 71, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (885, 'sx4', 'Sx4', 71, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (135, 'tacuma', 'Tacuma', 14, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (218, 'tacuma', 'Tacuma', 19, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (889, 'tagora', 'Tagora', 72, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (134, 'tahoe', 'Tahoe', 14, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (291, 'talento', 'Talento', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (964, 'taro', 'Taro', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (893, 'telco', 'Telco', 73, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (892, 'telcosport', 'Telcosport', 73, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (272, 'tempra', 'Tempra', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (225, 'terios', 'Terios', 21, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (817, 'terra', 'Terra', 66, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (364, 'terracan', 'Terracan', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (617, 'terrano', 'Terrano', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (616, 'terrano-ii', 'Terrano Ii', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (252, 'testarossa', 'Testarossa', 24, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (581, 'tf', 'Tf', 52, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (501, 'thar', 'Thar', 47, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (456, 'thema', 'Thema', 42, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (453, 'thesis', 'Thesis', 42, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (663, 'tigra', 'Tigra', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (961, 'tiguan', 'Tiguan', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (636, 'tiida', 'Tiida', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (268, 'tipo', 'Tipo', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (899, 'tl-pick-up', 'Tl Pick Up', 73, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (809, 'toledo', 'Toledo', 66, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (953, 'touareg', 'Touareg', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (954, 'touran', 'Touran', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (782, 'touring', 'Touring', 62, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (329, 'tourneo-custom', 'Tourneo Custom', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (638, 'trade', 'Trade', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (752, 'trafic', 'Trafic', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (136, 'trailblazer', 'Trailblazer', 14, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (362, 'trajet', 'Trajet', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (724, 'trans-am', 'Trans Am', 59, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (130, 'trans-sport', 'Trans Sport', 14, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (722, 'trans-sport', 'Trans Sport', 59, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (318, 'transit', 'Transit', 26, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (564, 'transporter', 'Transporter', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (962, 'transporter', 'Transporter', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (459, 'trevi', 'Trevi', 42, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (870, 'trezia', 'Trezia', 70, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (868, 'tribeca', 'Tribeca', 70, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (528, 'tribute', 'Tribute', 50, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (387, 'trooper', 'Trooper', 34, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (392, 'trroper', 'Trroper', 34, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (57, 'tt', 'Tt', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (74, 'tt-rs', 'Tt Rs', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (71, 'tts', 'Tts', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (367, 'tucson', 'Tucson', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (90, 'turbo', 'Turbo', 10, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (96, 'turbo-r', 'Turbo R', 10, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (740, 'twingo', 'Twingo', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (271, 'ulysse', 'Ulysse', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (270, 'uno', 'Uno', 25, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (972, 'up', 'Up', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (933, 'urban-cruiser', 'Urban Cruiser', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (987, 'v40', 'V40', 78, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (1004, 'v40-cross-country', 'V40 Cross Country', 78, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (988, 'v50', 'V50', 78, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (612, 'v6', 'V6', 55, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (1003, 'v60', 'V60', 78, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (977, 'v70', 'V70', 78, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (978, 'v70-classic', 'V70 Classic', 78, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (989, 'v70-xc', 'V70 Xc', 78, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (33, 'v8', 'V8', 6, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (67, 'v8', 'V8', 7, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (36, 'v8-vantage', 'V8 Vantage', 6, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (984, 'v90', 'V90', 78, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (552, 'vaneo', 'Vaneo', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (637, 'vanette', 'Vanette', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (639, 'vanette-cargo', 'Vanette Cargo', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (35, 'vanquish', 'Vanquish', 6, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (37, 'vantage', 'Vantage', 6, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (42, 'vantage-v12', 'Vantage V12', 6, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (41, 'vantage-v8', 'Vantage V8', 6, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (658, 'vectra', 'Vectra', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (747, 'vel-satis', 'Vel Satis', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (380, 'veloster', 'Veloster', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (431, 'venga', 'Venga', 39, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (944, 'vento', 'Vento', 77, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (931, 'verso', 'Verso', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (548, 'viano', 'Viano', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (151, 'viper', 'Viper', 15, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (232, 'viper', 'Viper', 23, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (40, 'virage', 'Virage', 6, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (190, 'visa', 'Visa', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (148, 'vision', 'Vision', 15, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (901, 'vista', 'Vista', 73, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (875, 'vitara', 'Vitara', 71, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (563, 'vito', 'Vito', 51, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (675, 'vivaro', 'Vivaro', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (39, 'volante', 'Volante', 6, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (146, 'volt', 'Volt', 14, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (153, 'voyager', 'Voyager', 15, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (463, 'voyager', 'Voyager', 42, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (879, 'wagon-r', 'Wagon R', 71, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (773, 'wind', 'Wind', 61, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (403, 'wrangler', 'Wrangler', 38, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (408, 'wrangler-unlimited', 'Wrangler Unlimited', 38, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (869, 'wrx-sti', 'Wrx Sti', 70, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (116, 'x1', 'X1', 12, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (112, 'x3', 'X3', 12, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (110, 'x5', 'X5', 12, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (115, 'x6', 'X6', 12, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (163, 'xantia', 'Xantia', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (1002, 'xc60', 'Xc60', 78, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (990, 'xc70', 'Xc70', 78, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (994, 'xc90', 'Xc90', 78, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (516, 'xedos-6', 'Xedos 6', 50, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (519, 'xedos-9', 'Xedos 9', 50, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (902, 'xenon', 'Xenon', 73, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (900, 'xenon-pick-up', 'Xenon Pick Up', 73, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (401, 'xf', 'Xf', 37, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (361, 'xg', 'Xg', 31, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (228, 'xj', 'Xj', 22, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (399, 'xj', 'Xj', 37, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (121, 'xlr', 'Xlr', 13, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (164, 'xm', 'Xm', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (171, 'xsara', 'Xsara', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (173, 'xsara-picasso', 'Xsara Picasso', 16, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (866, 'xt', 'Xt', 70, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (631, 'xtrail', 'Xtrail', 56, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (402, 'xtype', 'Xtype', 37, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (871, 'xv', 'Xv', 70, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (451, 'y', 'Y', 42, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (447, 'y10', 'Y10', 42, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (919, 'yaris', 'Yaris', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (920, 'yaris-verso', 'Yaris Verso', 74, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (835, 'yeti', 'Yeti', 67, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (452, 'ypsilon', 'Ypsilon', 42, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (462, 'ypsilon-elefantino', 'Ypsilon Elefantino', 42, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (450, 'z', 'Z', 42, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (114, 'z1', 'Z1', 12, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (107, 'z3', 'Z3', 12, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (108, 'z4', 'Z4', 12, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (109, 'z8', 'Z8', 12, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (666, 'zafira', 'Zafira', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (683, 'zafira-tourer', 'Zafira Tourer', 57, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (457, 'zeta', 'Zeta', 42, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (582, 'zr', 'Zr', 52, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (583, 'zs', 'Zs', 52, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (584, 'zt', 'Zt', 52, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (585, 'ztt', 'Ztt', 52, 1);
insert into modelo (modelo_id, clave, descripcion, marca_id, activo) values (166, 'zx', 'Zx', 16, 1);
