insert into PAIS (pais_id, nombre, clave, region) values (1, 'Anguila', 'AIA', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (2, 'Antigua y Barbuda', 'ATG', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (3, 'Argentina', 'ARG', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (4, 'Aruba', 'ABW', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (5, 'Bahamas', 'BHS', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (6, 'Barbados', 'BRB', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (7, 'Belice', 'BLZ', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (8, 'Bermudas', 'BMU', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (9, 'Bolivia', 'BOL', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (10, 'Bonaire', 'BES', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (11, 'Brasil', 'BRA', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (12, 'Canadá', 'CAN', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (13, 'Chile', 'CHL', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (14, 'Colombia', 'COL', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (15, 'Costa Rica', 'CRI', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (16, 'Cuba', 'CUB', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (17, 'Curazao', 'CUW', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (18, 'Dominica', 'DMA', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (19, 'Ecuador', 'ECU', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (20, 'El Salvador', 'SLV', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (21, 'Estados Unidos', 'USA', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (22, 'Granada', 'GRD', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (23, 'Groenlandia', 'GRL', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (24, 'Guadalupe', 'GLP', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (25, 'Guatemala', 'GTM', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (26, 'Guayana Francesa', 'GUF', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (27, 'Guyana', 'GUY', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (28, 'Haití', 'HTI', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (29, 'Honduras', 'HND', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (30, 'Islas Caimán', 'CYM', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (31, 'Islas Falkland (Malvinas)', 'FLK', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (32, 'Islas Turcas y Caicos', 'TCA', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (33, 'Islas Virgenes Británicas', 'VGB', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (34, 'Islas Virgenes de Los Estados Unidos', 'VIR', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (35, 'Jamaica', 'JAM', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (36, 'Martinica', 'MTQ', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (37, 'México', 'MEX', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (38, 'Montserrat', 'MSR', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (39, 'Nicaragua', 'NIC', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (40, 'Panamá', 'PAN', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (41, 'Paraguay', 'PRY', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (42, 'Perú', 'PER', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (43, 'Puerto Rico', 'PRI', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (44, 'República Dominicana', 'DOM', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (45, 'San Bartolomé', 'BLM', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (46, 'San Cristóbal y Nieves', 'KNA', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (47, 'San Martín (Parte Francesa)', 'MAF', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (48, 'San Pedro y Miquelón', 'SPM', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (49, 'San Vicente y Las Granadinas', 'VCT', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (50, 'Santa Lucía', 'LCA', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (51, 'Sint Maarten (Parte Neerlandesa)', 'SXM', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (52, 'Surinam', 'SUR', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (53, 'Trinidad y Tobago', 'TTO', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (54, 'Uruguay', 'URY', 'AME');
insert into PAIS (pais_id, nombre, clave, region) values (55, 'Venezuela', 'VEN', 'AME');
