insert into pais (pais_id, nombre, clave, region) values (56, 'Albania', 'ALB', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (57, 'Alemania', 'DEU', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (58, 'Andorra', 'AND', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (59, 'Austria', 'AUT', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (60, 'Bélgica', 'BEL', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (61, 'Bielorrusia', 'BLR', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (62, 'Bosnia y Herzegovina', 'BIH', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (63, 'Bulgaria', 'BGR', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (64, 'Croacia', 'HRV', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (65, 'Dinamarca', 'DNK', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (66, 'Eslovaquia', 'SVK', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (67, 'Eslovenia', 'SVN', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (68, 'España', 'ESP', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (69, 'Estonia', 'EST', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (70, 'Federacion Rusa', 'RUS', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (71, 'Finlandia', 'FIN', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (72, 'Francia', 'FRA', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (73, 'Gibraltar', 'GIB', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (74, 'Grecia', 'GRC', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (75, 'Guernsey', 'GGY', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (76, 'Hungría', 'HUN', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (77, 'Irlanda', 'IRL', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (78, 'Isla de Man', 'IMN', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (79, 'Islandia', 'ISL', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (80, 'Islas Åland', 'ALA', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (81, 'Islas Feroe', 'FRO', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (82, 'Italia', 'ITA', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (83, 'Jersey', 'JEY', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (84, 'Letonia', 'LVA', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (85, 'Liechtenstein', 'LIE', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (86, 'Lituania', 'LTU', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (87, 'Luxemburgo', 'LUX', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (88, 'Macedonia', 'MKD', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (89, 'Malta', 'MLT', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (90, 'Moldavia', 'MDA', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (91, 'Mónaco', 'MCO', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (92, 'Montenegro', 'MNE', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (93, 'Noruega', 'NOR', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (94, 'Países Bajos', 'NLD', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (95, 'Polonia', 'POL', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (96, 'Portugal', 'PRT', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (97, 'Reino Unido', 'GBR', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (98, 'República Checa', 'CZE', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (99, 'Rumania', 'ROU', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (100, 'San Marino', 'SMR', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (101, 'Santa Sede (Ciudad Estado Vaticano)', 'VAT', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (102, 'Serbia', 'SRB', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (103, 'Suecia', 'SWE', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (104, '  Suiza', 'CHE', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (105, 'Svalbard y Jan Mayen', 'SJM', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (106, 'Turquía', 'TUR', 'EUR');
insert into pais (pais_id, nombre, clave, region) values (107, 'Ucrania', 'UKR', 'EUR');
